### ISSUE TITLE
Broken file paths for images

### ISSUE THREAD

**Issue by Noah-T** [cindyloo/familyreunion#1]
//these are the missing files
http://www.pastportinteractive.com/storybot/img/avatar_generic.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.pastportinteractive.com/storybot/img/info_btn.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.pastportinteractive.com/storybot/img/keyboard_keys.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by cindyloo** [comment]
uploaded! 

```
  From: Noah Teshu <notifications@github.com>
```

 To: cindyloo/familyreunion familyreunion@noreply.github.com 
 Sent: Thursday, February 5, 2015 10:30 AM
 Subject: [familyreunion] Broken file paths for images (#1)

//these are the missing files
http://www.pastportinteractive.com/storybot/img/avatar_generic.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.pastportinteractive.com/storybot/img/info_btn.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.pastportinteractive.com/storybot/img/keyboard_keys.png Failed to load resource: the server responded with a status of 404 (Not Found)—

**Comment by Noah-T** [comment]
Great!

**Comment by Noah-T** [comment]
I got the ftp login working. Thanks!

On Thu, Feb 5, 2015 at 11:24 AM, cindyb notifications@github.com wrote:

> uploaded! I also created a ftp upload so you can push from Github when you
> want, if you want. 
> 
> From: Noah Teshu notifications@github.com
> To: cindyloo/familyreunion familyreunion@noreply.github.com
> Sent: Thursday, February 5, 2015 10:30 AM
> Subject: [familyreunion] Broken file paths for images (#1)
> 
> //these are the missing files
> http://www.pastportinteractive.com/storybot/img/avatar_generic.png Failed
> to load resource: the server responded with a status of 404 (Not Found)
> http://www.pastportinteractive.com/storybot/img/info_btn.png Failed to
> load resource: the server responded with a status of 404 (Not Found)
> http://www.pastportinteractive.com/storybot/img/keyboard_keys.png Failed
> to load resource: the server responded with a status of 404 (Not Found)—
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cindyloo/familyreunion/issues/1#issuecomment-73075798
> .

## 

Noah Teshu

617-694-0187
http://www.noahteshu.comwww.noahteshu.com
http://noahteshu.com/fr_home.cfm
